CREATE TABLE IF NOT EXISTS customers (
    id         INT PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(100) NOT NULL,
    phone      VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);